services:
  db:
    image: postgres:15-alpine
    container_name: puribot_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: puribot_queue
    environment:
      RABBITMQ_DEFAULT_USER: ${DB_USER}
      RABBITMQ_DEFAULT_PASS: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"